// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAjan246mZMRQHb2GTge4WUZU7EkoyMpKI',
    appId: '1:167811838428:web:c8b386b12c4b12ffd4df19',
    messagingSenderId: '167811838428',
    projectId: 'task-management-5f898',
    authDomain: 'task-management-5f898.firebaseapp.com',
    storageBucket: 'task-management-5f898.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDfaJmgA5ijYXM_Ddcoi_BQtYoj2bqThnQ',
    appId: '1:167811838428:android:c9d516ba05a60078d4df19',
    messagingSenderId: '167811838428',
    projectId: 'task-management-5f898',
    storageBucket: 'task-management-5f898.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBALgt838UDrwWyEAoAP7UcV8_nW_00CXE',
    appId: '1:167811838428:ios:3186f17d018f43bfd4df19',
    messagingSenderId: '167811838428',
    projectId: 'task-management-5f898',
    storageBucket: 'task-management-5f898.appspot.com',
    iosBundleId: 'com.example.taskManagement',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBALgt838UDrwWyEAoAP7UcV8_nW_00CXE',
    appId: '1:167811838428:ios:83e78a450ec2ca01d4df19',
    messagingSenderId: '167811838428',
    projectId: 'task-management-5f898',
    storageBucket: 'task-management-5f898.appspot.com',
    iosBundleId: 'com.example.taskManagement.RunnerTests',
  );
}
